package com.iptv

import com.lagradost.cloudstream3.ErrorLoadingException
import com.lagradost.cloudstream3.HomePageList
import com.lagradost.cloudstream3.HomePageResponse
import com.lagradost.cloudstream3.LoadResponse
import com.lagradost.cloudstream3.MainAPI
import com.lagradost.cloudstream3.MainPageRequest
import com.lagradost.cloudstream3.SearchResponse
import com.lagradost.cloudstream3.SubtitleFile
import com.lagradost.cloudstream3.TvType
import com.lagradost.cloudstream3.app
import com.lagradost.cloudstream3.newHomePageResponse
import com.lagradost.cloudstream3.newLiveSearchResponse
import com.lagradost.cloudstream3.newLiveStreamLoadResponse
import com.lagradost.cloudstream3.utils.AppUtils.parseJson
import com.lagradost.cloudstream3.utils.AppUtils.toJson
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.ExtractorLinkType
import com.lagradost.cloudstream3.utils.Qualities
import com.lagradost.cloudstream3.utils.newExtractorLink

private const val TAG = "IPTV"

/**
 * Single channel entry parsed from the iptv-org M3U playlist.
 * Serialized as JSON between [getMainPage]/[search] -> [load] -> [loadLinks]
 * via CloudStream's `dataUrl` mechanism, so we don't have to re-parse the M3U
 * each time the user clicks a channel.
 */
data class IptvChannel(
    val name: String,
    val url: String,
    val logo: String? = null,
    val group: String? = null,
    val tvgId: String? = null,
    val userAgent: String? = null,
    val referrer: String? = null,
)

class IPTV : MainAPI() {
    override var mainUrl = "https://iptv-org.github.io"
    override var name = "IPTV Indonesia"
    override var lang = "id"
    override val supportedTypes = setOf(TvType.Live)
    override val hasMainPage = true
    override val hasChromecastSupport = true
    override val hasQuickSearch = true

    // The Indonesia-only country playlist generated by iptv-org. Single source
    // of truth: every entry already includes stream URL, logo, group, and any
    // required UA / Referer (via #EXTVLCOPT).
    private val playlistUrl = "$mainUrl/iptv/countries/id.m3u"

    // ---- In-memory cache ----------------------------------------------------
    // The upstream M3U is regenerated by iptv-org once per day. Caching the
    // parsed list for 1 hour avoids re-downloading ~50 KB on every keystroke
    // in search and every navigation in the home page.
    @Volatile private var cache: List<IptvChannel>? = null
    @Volatile private var cacheTime: Long = 0L
    private val cacheTtlMs: Long = 60 * 60 * 1000L // 1 hour

    private suspend fun loadAll(): List<IptvChannel> {
        val now = System.currentTimeMillis()
        cache?.let { if (now - cacheTime < cacheTtlMs) return it }

        val text = try {
            app.get(playlistUrl).text
        } catch (e: Exception) {
            println("$TAG: loadAll: failed to fetch playlist - ${e.message}")
            return cache ?: emptyList()
        }

        val parsed = parseM3U(text)
        if (parsed.isEmpty()) {
            println("$TAG: loadAll: parser returned 0 channels (response size=${text.length})")
            return cache ?: emptyList()
        }
        cache = parsed
        cacheTime = now
        println("$TAG: loadAll: parsed ${parsed.size} channels")
        return parsed
    }

    // Display order for category rows. Anything not listed falls to the bottom
    // and is then sorted alphabetically.
    private val groupOrder = listOf(
        "News", "General", "Entertainment", "Movies", "Series",
        "Music", "Sports", "Kids", "Education", "Documentary",
        "Lifestyle", "Culture", "Travel", "Cooking", "Comedy",
        "Religious", "Business", "Auto", "Outdoor", "Animation",
        "Family", "Weather", "Legislative", "Shop"
    )

    // Curated list of mainstream Indonesian TV channels. Order here is the
    // order shown to the user. Matched against parsed channel names with
    // tolerant comparison (spaces/dots/case ignored).
    private val popularNames = listOf(
        "Indosiar", "SCTV", "RCTI", "Trans 7", "Trans TV",
        "GTV", "MNC TV", "ANTV", "iNews", "tvOne",
        "Kompas TV", "NET.", "Metro TV", "RTV", "MDTV"
    )

    private fun normalizeForMatch(s: String): String =
        s.lowercase().replace(Regex("[\\s.\\-_]"), "")

    override suspend fun getMainPage(page: Int, request: MainPageRequest): HomePageResponse {
        val all = loadAll()
        if (all.isEmpty()) {
            throw ErrorLoadingException("Tidak dapat memuat daftar channel IPTV. Cek koneksi internet.")
        }

        // Build a normalized-name lookup so multiple feeds of the same channel
        // (e.g. "Trans TV (720p)" and "Trans TV (1080p)") are both reachable
        // — we keep the highest-quality / first match per popular name.
        val popularRow = popularNames.mapNotNull { wanted ->
            val target = normalizeForMatch(wanted)
            all.firstOrNull { normalizeForMatch(it.name) == target }
                ?: all.firstOrNull { normalizeForMatch(it.name).startsWith(target) }
                ?: all.firstOrNull { normalizeForMatch(it.name).contains(target) }
        }.distinctBy { it.url }

        val grouped = all.groupBy { it.group?.takeIf { g -> g.isNotBlank() } ?: "Lainnya" }

        val groupRows = grouped.entries
            .sortedWith(
                compareBy(
                    { groupOrder.indexOf(it.key).let { idx -> if (idx == -1) Int.MAX_VALUE else idx } },
                    { it.key.lowercase() }
                )
            )
            .map { (group, items) ->
                HomePageList(
                    name = group,
                    list = items.map { it.toLiveSearchResponse() },
                    isHorizontalImages = true
                )
            }

        val rows = buildList {
            if (popularRow.isNotEmpty()) {
                add(
                    HomePageList(
                        name = "Popular",
                        list = popularRow.map { it.toLiveSearchResponse() },
                        isHorizontalImages = true
                    )
                )
            }
            addAll(groupRows)
        }

        return newHomePageResponse(rows, hasNext = false)
    }

    private fun IptvChannel.toLiveSearchResponse(): SearchResponse =
        newLiveSearchResponse(name, toJson(), TvType.Live, fix = false) {
            posterUrl = logo
        }

    override suspend fun search(query: String): List<SearchResponse> {
        if (query.isBlank()) return emptyList()
        return loadAll()
            .filter {
                it.name.contains(query, ignoreCase = true) ||
                    (it.tvgId?.contains(query, ignoreCase = true) == true) ||
                    (it.group?.contains(query, ignoreCase = true) == true)
            }
            .map { entry ->
                newLiveSearchResponse(
                    entry.name,
                    entry.toJson(),
                    TvType.Live,
                    fix = false
                ) { posterUrl = entry.logo }
            }
    }

    override suspend fun quickSearch(query: String): List<SearchResponse> = search(query)

    override suspend fun load(url: String): LoadResponse {
        val entry = runCatching { parseJson<IptvChannel>(url) }.getOrNull()
            ?: throw ErrorLoadingException("Data channel tidak valid")

        val plotLines = listOfNotNull(
            entry.group?.let { "Kategori: $it" },
            entry.tvgId?.let { "Channel ID: $it" }
        )

        // We pass the original JSON as both `url` (so CloudStream has a stable
        // identifier for history/favourites) and `dataUrl` (which is forwarded
        // to loadLinks unchanged).
        return newLiveStreamLoadResponse(entry.name, url, url) {
            posterUrl = entry.logo
            plot = plotLines.joinToString("\n").ifBlank { null }
            tags = listOfNotNull(entry.group)
        }
    }

    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        val entry = runCatching { parseJson<IptvChannel>(data) }.getOrNull() ?: return false
        println("$TAG: loadLinks: name=${entry.name} url=${entry.url}")

        val type = when {
            entry.url.contains(".mpd", ignoreCase = true) -> ExtractorLinkType.DASH
            else -> ExtractorLinkType.M3U8
        }

        val extraHeaders = buildMap<String, String> {
            entry.userAgent?.let { put("User-Agent", it) }
        }

        callback.invoke(
            newExtractorLink(name, entry.name, entry.url, type) {
                this.referer = entry.referrer ?: ""
                this.quality = Qualities.Unknown.value
                if (extraHeaders.isNotEmpty()) this.headers = extraHeaders
            }
        )
        return true
    }

    // ---- M3U parser ---------------------------------------------------------
    // Standalone, dependency-free parser for the iptv-org extended M3U format.
    // Supports:
    //   - #EXTM3U header
    //   - #EXTINF attributes: tvg-id, tvg-logo, tvg-name, group-title,
    //                         http-user-agent, http-referrer
    //   - #EXTVLCOPT lines (VLC-style options) above the URL line
    //   - Pipe-encoded URL params (URL|User-Agent=...&Referer=...)
    private fun parseM3U(content: String): List<IptvChannel> {
        val lines = content.lineSequence()
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .toList()

        if (lines.firstOrNull()?.startsWith("#EXTM3U", ignoreCase = true) != true) {
            println("$TAG: parseM3U: missing #EXTM3U header")
            return emptyList()
        }

        val out = mutableListOf<IptvChannel>()
        var i = 1
        while (i < lines.size) {
            val line = lines[i]
            if (!line.startsWith("#EXTINF", ignoreCase = true)) {
                i++
                continue
            }

            val attrs = parseExtInfAttrs(line)
            val title = line.substringAfter(",").trim()
                .ifBlank { attrs["tvg-name"] ?: "Unknown" }

            var ua: String? = attrs["http-user-agent"]
            var ref: String? = attrs["http-referrer"]

            // Skip over any number of #EXT* / comment lines until we find the URL.
            var j = i + 1
            while (j < lines.size && lines[j].startsWith("#")) {
                val opt = lines[j]
                if (opt.startsWith("#EXTVLCOPT", ignoreCase = true)) {
                    val payload = opt.substringAfter(":", "")
                    val eq = payload.indexOf('=')
                    if (eq != -1) {
                        val key = payload.substring(0, eq).trim().lowercase()
                        val value = payload.substring(eq + 1).trim()
                            .removeSurrounding("\"")
                        when (key) {
                            "http-user-agent" -> ua = value
                            "http-referrer" -> ref = value
                        }
                    }
                }
                j++
            }

            if (j >= lines.size) break

            val (url, urlUa, urlRef) = parseUrlLine(lines[j])
            if (url.isBlank()) {
                i = j + 1
                continue
            }

            // Strip "(1080p)" / "(720p)" suffixes and "[Geo-blocked]" /
            // "[Not 24/7]" badges that iptv-org adds to channel names.
            val cleanedName = title
                .replace(Regex("""\s*\(\d+[pi]?\)""", RegexOption.IGNORE_CASE), "")
                .replace(Regex("""\s*\[[^\]]+]"""), "")
                .trim()
                .ifBlank { title }

            out.add(
                IptvChannel(
                    name = cleanedName,
                    url = url,
                    logo = attrs["tvg-logo"]?.takeIf { it.isNotBlank() },
                    group = attrs["group-title"]?.takeIf { it.isNotBlank() },
                    tvgId = attrs["tvg-id"]?.takeIf { it.isNotBlank() },
                    userAgent = urlUa ?: ua,
                    referrer = urlRef ?: ref,
                )
            )
            i = j + 1
        }
        return out
    }

    private val attrRegex = Regex("""([A-Za-z0-9_-]+)="([^"]*)"""")

    private fun parseExtInfAttrs(line: String): Map<String, String> {
        // Slice between `:-1` (or `:0`) and the comma that introduces the title.
        val afterColon = line.substringAfter(":", "")
        val attrPart = afterColon.substringBefore(",", afterColon)
            .let { it.dropWhile { ch -> ch == '-' || ch.isDigit() } }
            .trim()
        return attrRegex.findAll(attrPart)
            .associate { it.groupValues[1].lowercase() to it.groupValues[2] }
    }

    /**
     * Parse a stream URL line that may contain pipe-encoded HTTP options:
     *
     *   http://host/stream.m3u8|User-Agent=Mozilla/5.0&Referer=https://x/
     *
     * Returns Triple<url, userAgent?, referrer?>.
     */
    private fun parseUrlLine(line: String): Triple<String, String?, String?> {
        val pipeIdx = line.indexOf('|')
        if (pipeIdx == -1) return Triple(line, null, null)
        val url = line.substring(0, pipeIdx).trim()
        val params = line.substring(pipeIdx + 1).split('&')
            .mapNotNull {
                val eq = it.indexOf('=')
                if (eq == -1) null
                else it.substring(0, eq).trim().lowercase() to it.substring(eq + 1).trim()
            }
            .toMap()
        return Triple(url, params["user-agent"], params["referer"] ?: params["referrer"])
    }
}
